export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"


export const REGISTER_BEGIN = "REGISTER_BEGIN"
export const REGISTER_SUCESS = "REGISTER_SUCESS"
export const REGISTER_ERRORS = "REGISTER_ERRORS"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCESS = "LOGIN_USER_SUCESS"
export const LOGIN_USER_ERRORS = "LOGIN_USER_ERRORS"